apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: neptune-10ab
  name: neptune-10ab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neptune-10ab
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: neptune-10ab
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: httpd
        resources: {}
