apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-08-27T23:34:38Z"
  labels:
    run: busybox
  name: busybox
  namespace: default
  resourceVersion: "180480"
  uid: 5eeed1cc-f9ac-47f5-9b5e-d14ebabfc78a
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600s
    image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ljfpl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ckad
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-ljfpl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-08-27T23:34:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-08-27T23:34:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-08-27T23:34:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-08-27T23:34:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f75bbe3a23efadabd40528fc2b43f5c4c22f2be4c73ecf20ca373d2bb2fb374d
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7
    lastState: {}
    name: busybox
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-08-27T23:34:40Z"
  hostIP: 192.168.85.2
  phase: Running
  podIP: 10.244.0.64
  podIPs:
  - ip: 10.244.0.64
  qosClass: BestEffort
  startTime: "2024-08-27T23:34:38Z"
